// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlEPSy-Wv6Y07Wm7QA4tx8rqdxoVoi3lU',
    appId: '1:210216391225:web:bf5e2bb8b884428796f3e8',
    messagingSenderId: '210216391225',
    projectId: 'mobile-uts-soal-2',
    authDomain: 'mobile-uts-soal-2.firebaseapp.com',
    storageBucket: 'mobile-uts-soal-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMI1UwgEtS18pbNBYbbZC3-u9FrR7tHiE',
    appId: '1:210216391225:android:80cb90c643b7bdce96f3e8',
    messagingSenderId: '210216391225',
    projectId: 'mobile-uts-soal-2',
    storageBucket: 'mobile-uts-soal-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPhoKcvAsCq_APcBO8JKvbyrk7JmVc-wk',
    appId: '1:210216391225:ios:d19f5afeb97164db96f3e8',
    messagingSenderId: '210216391225',
    projectId: 'mobile-uts-soal-2',
    storageBucket: 'mobile-uts-soal-2.firebasestorage.app',
    iosBundleId: 'com.example.bungacintaUts2Mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPhoKcvAsCq_APcBO8JKvbyrk7JmVc-wk',
    appId: '1:210216391225:ios:d19f5afeb97164db96f3e8',
    messagingSenderId: '210216391225',
    projectId: 'mobile-uts-soal-2',
    storageBucket: 'mobile-uts-soal-2.firebasestorage.app',
    iosBundleId: 'com.example.bungacintaUts2Mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlEPSy-Wv6Y07Wm7QA4tx8rqdxoVoi3lU',
    appId: '1:210216391225:web:0e2ea18c1b3c43ba96f3e8',
    messagingSenderId: '210216391225',
    projectId: 'mobile-uts-soal-2',
    authDomain: 'mobile-uts-soal-2.firebaseapp.com',
    storageBucket: 'mobile-uts-soal-2.firebasestorage.app',
  );

}